ci: Add support for bootc end-to-end validation tests
These tests run the role during a bootc container image build, deploy
the container into a QEMU VM, boot that, and validate the expected
configuration there. They run in two different tox environments, and
thus have to be run in two steps (preparation in buildah, validation in
QEMU). The preparation is expected to output a qcow2 image in
`tests/tmp/TESTNAME/qcow2/disk.qcow2`, i.e. the output structure of
<https://github.com/osbuild/bootc-image-builder>.

These tests are tagged with `tests::bootc-e2` and are skipped in the
normal qemu-* scenarios. They run as part of the container-* ones. In
the container scenario, run the QEMU validation as a separate step in
the workflow.

See https://issues.redhat.com/browse/RHEL-88396

diff --git a/.github/workflows/qemu-kvm-integration-tests.yml b/.github/workflows/qemu-kvm-integration-tests.yml
--- a/.github/workflows/qemu-kvm-integration-tests.yml
+++ b/.github/workflows/qemu-kvm-integration-tests.yml
@@ -137,7 +137,7 @@ jobs:
         if: steps.check_platform.outputs.supported && startsWith(matrix.scenario.env, 'qemu')
         run: >-
           tox -e ${{ matrix.scenario.env }} -- --image-name ${{ matrix.scenario.image }} --make-batch
-          --log-level debug $TOX_ARGS
+          --log-level debug $TOX_ARGS --skip-tags tests::bootc-e2e
           --lsr-report-errors-url DEFAULT --
 
       - name: Qemu result summary
@@ -183,6 +183,32 @@ jobs:
               fi
           done
           exit $rc
+
+      - name: Run bootc validation tests in QEMU
+        if: steps.check_platform.outputs.supported &&
+            startsWith(matrix.scenario.env, 'container') &&
+            endsWith(matrix.scenario.image, '-bootc')
+        run: |
+          set -euxo pipefail
+          env=$(echo "${{ matrix.scenario.env }}" | sed 's/^container-/qemu-/')
+
+          for t in $(grep -wl tests::bootc-e2e tests/tests_*.yml); do
+              test=$(basename ${t%.yml})
+              image_file="$(pwd)/tests/tmp/$test/qcow2/disk.qcow2"
+              if [ ! -e "$image_file" ]; then
+                  echo "Missing $image_file" >&2
+                  exit 1
+              fi
+
+              if tox -e "$env" -- --image-file "$image_file" \
+                     --log-level debug $TOX_ARGS \
+                     --lsr-report-errors-url DEFAULT -- "$t" >out 2>&1; then
+                  mv out "${t}-PASS.log"
+              else
+                  mv out "${t}-FAIL.log"
+                  exit 1
+              fi
+          done
 
       - name: Upload test logs on failure
         if: failure()
